# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: events.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65vents.proto\x12\x03rtb\"\x19\n\x06LogAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\xf3\x01\n\rBidRequestLog\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06imp_id\x18\x02 \x01(\t\x12\x12\n\nauction_id\x18\x03 \x01(\t\x12\x13\n\x0bsite_domain\x18\x04 \x01(\t\x12\x11\n\tsite_page\x18\x05 \x01(\t\x12\x14\n\x0cuser_country\x18\x06 \x01(\t\x12\x15\n\ruser_language\x18\x07 \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\x08 \x01(\t\x12\x14\n\x0c\x62\x61nner_width\x18\t \x01(\x05\x12\x15\n\rbanner_height\x18\n \x01(\x05\x12\x13\n\x0b\x66loor_price\x18\x0b \x01(\x02\"}\n\x06\x42idLog\x12\x16\n\x0e\x62id_request_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61mpaign_id\x18\x02 \x01(\x05\x12\x13\n\x0b\x63reative_id\x18\x03 \x01(\x05\x12\x11\n\tbid_price\x18\x04 \x01(\x02\x12\x0b\n\x03won\x18\x05 \x01(\x08\x12\x11\n\twin_price\x18\x06 \x01(\x02\"W\n\rImpressionLog\x12\x0e\n\x06\x62id_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61mpaign_id\x18\x02 \x01(\x05\x12\x13\n\x0b\x63reative_id\x18\x03 \x01(\x05\x12\x0c\n\x04\x63ost\x18\x04 \x01(\x02\"K\n\x08\x43lickLog\x12\x15\n\rimpression_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61mpaign_id\x18\x02 \x01(\x05\x12\x13\n\x0b\x63reative_id\x18\x03 \x01(\x05\x32\xbd\x01\n\x0b\x45ventLogger\x12\x30\n\rLogBidRequest\x12\x12.rtb.BidRequestLog\x1a\x0b.rtb.LogAck\x12\"\n\x06LogBid\x12\x0b.rtb.BidLog\x1a\x0b.rtb.LogAck\x12\x30\n\rLogImpression\x12\x12.rtb.ImpressionLog\x1a\x0b.rtb.LogAck\x12&\n\x08LogClick\x12\r.rtb.ClickLog\x1a\x0b.rtb.LogAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGACK']._serialized_start=21
  _globals['_LOGACK']._serialized_end=46
  _globals['_BIDREQUESTLOG']._serialized_start=49
  _globals['_BIDREQUESTLOG']._serialized_end=292
  _globals['_BIDLOG']._serialized_start=294
  _globals['_BIDLOG']._serialized_end=419
  _globals['_IMPRESSIONLOG']._serialized_start=421
  _globals['_IMPRESSIONLOG']._serialized_end=508
  _globals['_CLICKLOG']._serialized_start=510
  _globals['_CLICKLOG']._serialized_end=585
  _globals['_EVENTLOGGER']._serialized_start=588
  _globals['_EVENTLOGGER']._serialized_end=777
# @@protoc_insertion_point(module_scope)
